<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.v3.runner.console">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\agent\StealthDesk.Agent.Core\StealthDesk.Agent.Core.csproj" />
    <ProjectReference Include="..\..\agent\StealthDesk.Agent.Windows\StealthDesk.Agent.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="StealthDesk.Contracts.Devices" />
  </ItemGroup>
</Project>
