<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="NativeMethods.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\shared\StealthDesk.Libraries.Shared\StealthDesk.Libraries.Shared.csproj" />
  </ItemGroup>
</Project>