<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\frontend\StealthDesk.Web.Client\StealthDesk.Web.Client.csproj" />
    <ProjectReference Include="..\..\shared\StealthDesk.Web.ServiceDefaults\StealthDesk.Web.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\shared\StealthDesk.Libraries.Api.Contracts\StealthDesk.Libraries.Api.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\StealthDesk.Libraries.DataRedaction\StealthDesk.Libraries.DataRedaction.csproj" />
    <ProjectReference Include="..\..\shared\StealthDesk.Libraries.Shared\StealthDesk.Libraries.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
